import "./globals.css";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import Navbar from "@/components/AuthProvider/navbar/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="mx-auto max-w-[calc(100vw - 80px)] min-h-screen flex-row bg-gray-400 px-[40px] py-[10px]">
            <div className="w-full h-[50px] bg-blue-950 text-white ">
              <Navbar />
            </div>
            <div className="w-full min-h-screen bg-gray-200">{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
